// Dish/cuisine photography lookup.
//
// The source of truth for what a dish photo IS is public/images/ASSET-PROMPTS.md
// (189 planned shots); the source of truth for what's actually on disk right
// now is dish-images.data.json, a manifest generated by
// scratchpad/gen_manifest.py against the real files under public/images/
// cuisines/ and public/images/dishes/<id>/ after each asset drop. Re-run that
// script and commit the refreshed JSON whenever new photos land -- this file
// never scans the filesystem itself (Astro ships static assets, it doesn't
// read them back at runtime).
//
// THE MATCHING LOGIC, THREE PASSES, each only tried if the one before it
// missed:
//   1. Exact match (case/punctuation-insensitive) against the 170-dish
//      catalog, including either half of a "Name (Alt Name)" entry.
//   2. A small regional-synonym table (below) -- the same dish sometimes has
//      a genuinely different name by region (Puchka = Pani Puri = Golgappa
//      = Gupchup), which no amount of fuzzy text matching can bridge on its
//      own since the words don't overlap at all.
//   3. Word-overlap fuzzy match -- catches an AI-generated menu name that's
//      a real catalog dish with extra words tacked on ("Spicy Butter
//      Chicken Curry with Basmati Rice" still shares "butter"+"chicken"
//      with catalog entry "Butter Chicken"). Requires most of the catalog
//      dish's own words to be present, not just one word, specifically to
//      avoid a generic single-word coincidence (matching everything
//      described as a "curry" to one arbitrary curry photo).
// If all three miss -- true for most restaurant-menu items, since a live
// AI-generated menu produces far more variety than any fixed photo catalog
// could ever cover -- the cuisine's hero shot is used instead of the bare
// icon placeholder. That's real photography, honestly representing "this
// cuisine," never a fabricated claim that a specific unphotographed dish
// looks like whatever image happened to load.
import data from "./dish-images.data.json";

interface DishEntry {
  path: string;
  name: string;
  aliases: string[];
}

const DISH_DATA = data as { dishes: DishEntry[]; heroes: Record<string, string> };

function normalize(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const STOP_WORDS = new Set([
  "with", "and", "the", "a", "an", "of", "in", "style", "special", "fresh",
  "homemade", "traditional", "classic", "spicy", "mild", "creamy", "crispy",
]);

function significantWords(name: string): string[] {
  return normalize(name)
    .split(" ")
    .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
}

const DISH_ALIAS_MAP: Map<string, string> = new Map();
// name -> significant-word set, built once for the fuzzy pass.
const DISH_WORDS: Array<{ path: string; words: Set<string> }> = [];
// cuisineId -> every dish photo under /images/dishes/<cuisineId>/, for the
// per-restaurant image variant below.
const DISHES_BY_CUISINE: Map<string, string[]> = new Map();
for (const entry of DISH_DATA.dishes) {
  for (const alias of entry.aliases) {
    if (!DISH_ALIAS_MAP.has(alias)) DISH_ALIAS_MAP.set(alias, entry.path);
  }
  DISH_WORDS.push({ path: entry.path, words: new Set(significantWords(entry.name)) });
  const m = entry.path.match(/^\/images\/dishes\/([^/]+)\//);
  if (m) {
    const arr = DISHES_BY_CUISINE.get(m[1]) ?? [];
    arr.push(entry.path);
    DISHES_BY_CUISINE.set(m[1], arr);
  }
}

// Regional/language name variants for the same dish -- deliberately short.
// Add to this only for dishes actually seen colliding in practice (this
// list started with exactly one entry, added after a live menu served
// "Puchka" and the catalog only knows "Pani Puri"), not as a speculative
// exhaustive synonym dictionary for every dish.
const REGIONAL_SYNONYMS: Record<string, string> = {
  puchka: "pani puri",
  golgappa: "pani puri",
  gupchup: "pani puri",
  gol_gappe: "pani puri",
};

function applySynonyms(words: string[]): string[] {
  return words.map((w) => REGIONAL_SYNONYMS[w]?.split(" ")[0] ?? w);
}

/** A cuisine or Indian-subcuisine hero photo, if one has been generated. */
export function getCuisineHeroImage(cuisineId: string): string | undefined {
  return DISH_DATA.heroes[cuisineId];
}

/**
 * A stable, per-restaurant image for a matched cuisine. No real
 * per-restaurant photography exists (Google Places photos aren't plumbed
 * through), and using the single cuisine hero for every card made every
 * restaurant look identical. This spreads deterministically across that
 * cuisine's real dish photos, keyed by `seed` (the restaurant name), so each
 * card differs but stays the same across re-renders. Falls back to the
 * cuisine hero, then undefined (caller shows its icon), for a cuisine with
 * no dish-photo folder -- e.g. AI-suggested `ai-<slug>` ids.
 */
export function getCuisineImageVariant(cuisineId: string, seed: string): string | undefined {
  const pool = DISHES_BY_CUISINE.get(cuisineId);
  if (pool && pool.length > 0) {
    let hash = 0;
    for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
    return pool[hash % pool.length];
  }
  return getCuisineHeroImage(cuisineId);
}

/**
 * The specific dish photo for `dishName` if it matches the shot catalog
 * (exact, then regional-synonym, then word-overlap fuzzy -- see this file's
 * header for what each pass catches), else the `cuisineId` hero shot as a
 * stand-in, else undefined -- callers render their existing icon/emoji
 * placeholder in that last case.
 */
export function getDishImage(dishName: string, cuisineId: string): string | undefined {
  const normalized = normalize(dishName);
  const exact = DISH_ALIAS_MAP.get(normalized);
  if (exact) return exact;

  const queryWords = new Set(applySynonyms(significantWords(dishName)));
  if (queryWords.size > 0) {
    let best: { path: string; score: number } | null = null;
    for (const candidate of DISH_WORDS) {
      if (candidate.words.size === 0) continue;
      let overlap = 0;
      for (const w of candidate.words) if (queryWords.has(w)) overlap++;
      // Require most of the CATALOG dish's words to show up in the query,
      // not just one -- "chicken" alone matching a dozen different chicken
      // dishes is exactly the false-positive this threshold exists to
      // block (the same lesson from sorting ASSET-PROMPTS.md's photo drop
      // earlier in this project).
      const score = overlap / candidate.words.size;
      if (score >= 0.75 && (!best || score > best.score)) {
        best = { path: candidate.path, score };
      }
    }
    if (best) return best.path;
  }

  return getCuisineHeroImage(cuisineId);
}
