// Dish/cuisine photography lookup.
//
// The source of truth for what a dish photo IS is public/images/ASSET-PROMPTS.md
// (189 planned shots); the source of truth for what's actually on disk right
// now is dish-images.data.json, a manifest generated by
// scratchpad/gen_manifest.py against the real files under public/images/
// cuisines/ and public/images/dishes/<id>/ after each asset drop. Re-run that
// script and commit the refreshed JSON whenever new photos land -- this file
// never scans the filesystem itself (Astro ships static assets, it doesn't
// read them back at runtime).
//
// Lookup follows the fallback rule the manifest was written against: a swiped
// dish's name is looked up in the shot catalog first (dishName -> specific
// photo); a generative-menu dish that isn't in the catalog still gets *a*
// photo -- the matched cuisine's hero shot -- rather than falling through to
// the caller's bare icon placeholder. Some catalog entries carry an
// alternate/anglicized name in parens (e.g. "Goi Cuon (Spring Rolls)"); both
// halves are indexed as aliases so either name a menu might use resolves to
// the same photo.
import data from "./dish-images.data.json";

interface DishEntry {
  path: string;
  name: string;
  aliases: string[];
}

const DISH_DATA = data as { dishes: DishEntry[]; heroes: Record<string, string> };

function normalize(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const DISH_ALIAS_MAP: Map<string, string> = new Map();
for (const entry of DISH_DATA.dishes) {
  for (const alias of entry.aliases) {
    if (!DISH_ALIAS_MAP.has(alias)) DISH_ALIAS_MAP.set(alias, entry.path);
  }
}

/** A cuisine or Indian-subcuisine hero photo, if one has been generated. */
export function getCuisineHeroImage(cuisineId: string): string | undefined {
  return DISH_DATA.heroes[cuisineId];
}

/**
 * The specific dish photo for `dishName` if it matches the shot catalog
 * (case/punctuation-insensitive), else the `cuisineId` hero shot as a
 * stand-in, else undefined -- callers render their existing icon/emoji
 * placeholder in that last case.
 */
export function getDishImage(dishName: string, cuisineId: string): string | undefined {
  const hit = DISH_ALIAS_MAP.get(normalize(dishName));
  if (hit) return hit;
  return getCuisineHeroImage(cuisineId);
}
